import { Inter } from "next/font/google";
import "templates/app/globals.css";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
    title: "Foundation App",
    description: "Generated by create foundation app",
};
export default function RootLayout({ children, }) {
    return (<html lang="en">
      <body className={inter.className}>{children}</body>
    </html>);
}
